DW-000: Added color messages.

diff --git a/drupal_watcher b/drupal_watcher
--- a/drupal_watcher
+++ b/drupal_watcher
@@ -3,17 +3,23 @@
 # Get the list of plugins to verify
 plugins=(fswatch)
 
+# Define color variables
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NC='\033[0m' # No Color
+
 # Loop through the plugins
 for plugin in "${plugins[@]}"; do
-  echo "Verifying $plugin..."
+  echo -e "${GREEN}Verifying $plugin...${NC}"
 
   # Check if the plugin is installed
   if brew list "$plugin" &>/dev/null; then
-    echo "$plugin is installed."
+    echo -e "${GREEN}$plugin is installed.${NC}"
   else
-    echo "Installing $plugin..."
+    echo -e "${YELLOW}Installing $plugin...${NC}"
     brew install "$plugin"
-    echo "$plugin installed..."
+    echo -e "${GREEN}$plugin installed...${NC}"
   fi
 done
 
@@ -28,25 +34,25 @@ DRUSH="${FOLDER_BINARIES}/drush"
 # Action to perform when a file is modified
 ACTION="$DRUSH cr"  # Clear Drupal cache
 
-echo "Watching $FOLDER_MODULES_TO_WATCH and $FOLDER_THEMES_TO_WATCH for changes..."
+echo -e "${YELLOW}Watching $FOLDER_MODULES_TO_WATCH and $FOLDER_THEMES_TO_WATCH for changes...${NC}"
 
 # Check if the specified directory exists
 if [ ! -d "$WATCH_DIR" ]; then
-    echo "Error: Directory '$WATCH_DIR' does not exist."
+    echo -e "${RED}Error: Directory '$WATCH_DIR' does not exist.${NC}"
     exit 1
 fi
 
 # Check if Drush executable exists
 if [ ! -x "$DRUSH" ]; then
-    echo "Error: Drush executable not found at '$DRUSH'."
+    echo -e "${RED}Error: Drush executable not found at '$DRUSH'.${NC}"
     exit 1
 fi
 
 # Use fswatch to monitor the directories for file modifications
 fswatch -0 -e ".*" -i "\\.html\\.twig$" "$FOLDER_MODULES_TO_WATCH" "$FOLDER_THEMES_TO_WATCH" | while read -d "" modified_file; do
-    echo "File $modified_file was modified"
-    $ACTION || echo "Error: Failed to run '$ACTION'."
+    echo -e "${GREEN}File $modified_file was modified${NC}"
+    $ACTION || echo -e "${RED}Error: Failed to run '$ACTION'.${NC}"
     # Add a delay to ignore subsequent saves for a brief period
-    echo "waiting..."
+    echo -e "${YELLOW}waiting...${NC}"
     sleep 5
 done
